# Generated by Django 5.0.3 on 2025-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='specification',
            field=models.TextField(default='No specification provided'),
        ),
    ]
