# Generated by Django 5.0.3 on 2025-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_equipment_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='specification',
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
